In [16]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data',one_hot=True)

import tensorflow as tf
sess = tf.InteractiveSession()

x = tf.placeholder("float",shape=[None,784])
y_ = tf.placeholder("float",shape=[None,10])

# 因为这里没有隐藏层，只有输入与输出层，所以共有 784*10个权重需要训练
W = tf.Variable(tf.zeros([784,10]))
# 每个输出神经元都有一个偏置，即共有10个偏置需要训练
b = tf.Variable(tf.zeros([10]))

# tf中变量需要经过session初始化之后才能使用
sess.run(tf.initialize_all_variables())

# 类别预测


y = tf.nn.softmax(tf.matmul(x,W)+b)


# 使用交叉熵作为损失函数，这里计算的是整个minibanch的交叉熵
cross_entropy = -tf.reduce_sum(y_*tf.log(y))

# 使用梯度下降来优化目标函数
train_step = tf.train.GradientDescentOptimizer(0.01).minimize(cross_entropy)


for i in range(10000):
    batch = mnist.train.next_batch(50)
#   下面这两种写法的作用是一样的
#     sess.run(train_step,feed_dict={x:batch[0],y_:batch[1]})
    train_step.run(feed_dict={x:batch[0],y_:batch[1]})

# 此时 w与b均已经训练好了
print("W and b :",sess.run(W),sess.run(b))

# 图片类别的标签为[0,1,0,...] ，argmax直接拿到1的下标
correct_prediction = tf.equal(tf.argmax(y,1),tf.argmax(y_,1))

# 将bool类型的数据转换成float方便计算
accuracy = tf.reduce_mean(tf.cast(correct_prediction,"float"))


# 前面的操作都是定义图计算，eval相当于sess.run(),此时才启动计算
print(accuracy.eval(feed_dict={x:mnist.test.images,y_:mnist.test.labels}))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
W and b : [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] [-1.0534542   0.9049066   0.24249396 -0.60114217  0.01192631  2.4154193
 -0.39152515  1.4117808  -2.4513316  -0.48906305]
0.9206
